import smtplib
from email.message import EmailMessage

from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.application import MIMEApplication
from email.mime.audio import MIMEAudio
from email.mime.image import MIMEImage
from email.mime.base import MIMEBase
from email import encoders

from datetime import date

# set your email and password
# please use App Password
def email_sent():


    # create email
    email_address = "research.niblace@gmail.com"
    email_password = "xladtuspqhbvliqy"
    # set your email and password
    # please use App Password

    # create email
    # msg = EmailMessage()
    msg = MIMEMultipart()
    msg['Subject'] = "Email subject"
    msg['From'] = 'research.niblace@gmail.com' 
    msg['To'] = "abhishek@niblcapital.com"
    msg['To'] = "tiwarilaxuu@gmail.com"
    msg['To'] = 'subhash@niblcapital.com'
    # msg.set_content("This is eamil message")
    # print(dir(msg))
    body = f"Daily Update Report {date.today()}, It is generated by Python "

    msg.attach(MIMEText(body, 'plain'))

    filename = f"Top 7 broker List with its Turnover {date.today()}.xlsx"
    attachment = open(f"Daily_Report/Top 7 broker List with its Turnover {date.today()}.xlsx", "rb")

    part = MIMEBase('application', 'octet-stream')
    part.set_payload((attachment).read())
    encoders.encode_base64(part)
    part.add_header('Content-Disposition', "attachment; filename= %s" % filename)

    msg.attach(part)


    # send email
    with smtplib.SMTP_SSL('smtp.gmail.com', 465) as smtp:
        smtp.login(email_address, email_password)
        smtp.send_message(msg)
    print('Email send successfully')


